SELECT * FROM NOTICE_VIEWSELECT ROW_NUMVBER()






SELECT CODE, TITLE, WRITER, CONTENT, REGDATE, HIT, CMTCNT
FROM
   NOTICE N OUTER LEFT JOIN COMMENT C
   ON N.CODE = C.NOTICE_CODE
   GROUP CODE, TITLE, WRITER, CONTENT, REGDATE, HIT
   
--SELECT NVL(MAX(TO_NUMBER(CODE)), 0) FROM NOTICE

SELECT ISNULL(MAX(CAST(CODE AS INT)),1) FROM NOTICES

SELECT * FROM(
	SELECT
	ROW_NUMBER() OVER(ORDER BY REGDATE DESC) NUM,
	NOTICES_VIEW.*FROM NOTICES_VIEW
	WHERE TITLE LIKE '%%'
)N
WHERE NUM BETWEEN 1 AND 10;

